version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor:
      - isblues
    steps:
      - step: build@php
        name: build_php
        displayName: PHP 构建
        phpVersion: '8.3'
        commands:
          - '# 设置全局composer依赖仓库地址'
          - composer config -g secure-http false
          - composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
          - composer install
          - php -v
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        strategy: {}
